

# these contian the default shard sets
# Used to allow automatic access to them
# Without querying the api if the shard exists or not
# These also do not support any extra arguments, atleast not yet'
# To use those, use get_shards with Shard Objects

nation_shards = ('admirable',
 'animal',
 'animaltrait',
 'banner',
 'banners',
 'capital',
 'category',
 'census',
 'crime',
 'currency',
 'customleader',
 'customcapital',
 'customreligion',
 'dbid',
 'deaths',
 'demonym',
 'demonym2',
 'demonym2plural',
 'dispatches',
 'dispatchlist',
 'endorsements',
 'factbooks',
 'factbooklist',
 'firstlogin',
 'flag',
 'founded',
 'foundedtime',
 'freedom',
 'fullname',
 'gavote',
 'gdp',
 'govt',
 'govtdesc',
 'govtpriority',
 'happenings',
 'income',
 'industrydesc',
 'influence',
 'lastactivity',
 'lastlogin',
 'leader',
 'legislation',
 'majorindustry',
 'motto',
 'name',
 'notable',
 'policies',
 'poorest',
 'population',
 'publicsector',
 'rcensus',
 'region',
 'religion',
 'richest',
 'scvote',
 'sectors',
 'sensibilities',
 'tax',
 'tgcanrecruit',
 'tgcancampaign',
 'type',
 'wa',
 'wabadges',
 'wcensus')

region_shards = ('census',
 'censusranks',
 'dbid',
 'delegate',
 'delegateauth',
 'delegatevotes',
 'dispatches',
 'embassies',
 'embassyrmb',
 'factbook',
 'flag',
 'founded',
 'foundedtime',
 'founder',
 'founderauth',
 'gavote',
 'happenings',
 'history',
 'lastupdate',
 'messages',
 'name',
 'nations',
 'numnations',
 'officers',
 'poll',
 'power',
 'scvote',
 'tags',
 'wabadges',
 'zombie')

world_shards = ('banner',
 'census',
 'censusid',
 'censusdesc',
 'censusname',
 'censusranks',
 'censusscale',
 'censustitle',
 'dispatch',
 'dispatchlist',
 'faction',
 'factions',
 'featuredregion',
 'happenings',
 'lasteventid',
 'nations',
 'newnations',
 'numnations',
 'numregions',
 'poll',
 'regions',
 'regionsbytag',
 'tgqueue')

wa_shards = ('numnations',
 'numdelegates',
 'delegates',
 'members',
 'happenings',
 'proposals',
 'resolution',
 'voters',
 'votetrack',
 'dellog',
 'delvotes',
 'lastresolution')

individual_cards_shards = (
	'info',
	'markets',
	'owners',
	'trades'
	)